ModelSurge/sd-webui-comfyui

- install_comfyui.py
I think this was a potential issue IIRC
> install location

- lib_comfyui/argv_conversion.py
- lib_comfyui/webui_settings.py
- lib_comfyui/webui_tab.py
- preload.py
> fix: `--comfyui-listen` is str

- javascript/compute-height.js
Needs a slight refactor but now we don't have to wait for comfyui to load if it loads after the webui.
> reload <object> on error

- comfyui_custom_nodes/webui_postprocess_input.py
- comfyui_custom_nodes/webui_postprocess_output.py
- lib_comfyui/webui_callbacks.py
- scripts/comfyui.py
Merge this when the following PR is in the webui main:
- https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11957
> use postprocess_batch_list to overwrite batch images

- comfyui_custom_nodes/webui_save_image.py
- lib_comfyui/webui/paths.py
> dont import webui stuff

- lib_comfyui/comfyui/iframe_requests.py
- lib_comfyui/global_state.py
- lib_comfyui/webui/proxies.py
- lib_comfyui/webui/settings.py
> fix staticmethod order

- lib_comfyui/comfyui/iframe_requests.py
- lib_comfyui/external_code.py
- lib_comfyui/private/external_code.py
- scripts/comfyui.py
- Do not run a workflow type when the default workflow is loaded
- Do not add a workflow type to png info then it is the default workflow
- Load the default workflow for any missing workflow type in png info
related: #118
> Do not run empty workflows

- lib_comfyui/webui/workflow_patcher.py
> fix img2img invert

- lib_comfyui/ipc/strategies.py
https://superuser.com/a/1056948
> osx doesn't have tmpfs

- comfyui_custom_scripts/extensions/webuiNodes.js
- comfyui_custom_scripts/extensions/webuiRequests.js
This is a workaround. We need websockets for a proper fix.
> fix: wait at most 2 seconds before giving up on the webui-comfyui clients handshake

- comfyui_custom_nodes/webui_io.py
- comfyui_custom_scripts/extensions/webuiNodes.js
- javascript/compute-height.js
- lib_comfyui/comfyui/iframe_requests.py
- lib_comfyui/comfyui/queue_tracker.py
- lib_comfyui/external_code/api.py
- lib_comfyui/webui/accordion.py
- lib_comfyui/webui/gradio_utils.py
- lib_comfyui/webui/tab.py
- lib_comfyui/webui/workflow_patcher.py
- scripts/comfyui.py
- style.css
- "Enable" checkbox to determine whether the currently displayed workflow type is enabled
- show in green in the dropdown which of the workflow types are currently enabled
closes #118 
closes #103
> Enable checkbox

- lib_comfyui/webui/workflow_patcher.py
> fix: img2img

- lib_comfyui/webui/workflow_patcher.py
> Fix img2img

- comfyui_custom_scripts/extensions/webuiNodes.js
- comfyui_custom_scripts/extensions/webuiPatches.js
- javascript/compute-height.js
- lib_comfyui/webui/patches.py
- scripts/comfyui.py
- skip workflow conversion when a workflow is not enabled
- fix default workflow not loading upon clicking on the reload button for newer comfyui versions
- fix postprocess duplicating of the 4 attributes on p
closes #151
> Fix for webui 1.6.0

- lib_comfyui/webui/settings.py
> canonicalize client url

- lib_comfyui/comfyui/pre_main.py
- lib_comfyui/comfyui_process.py
- lib_comfyui/webui/settings.py
https://github.com/comfyanonymous/ComfyUI/commit/3039b08eb16777431946ed9ae4a63c5466336bff
closes #160 
related: #161
> fix args in newer comfyui versions

- lib_comfyui/ipc/strategies.py
> Use BytesLike instead

- javascript/compute-height.js
- lib_comfyui/comfyui/iframe_requests.py
- lib_comfyui/global_state.py
- lib_comfyui/webui/tab.py
- scripts/comfyui.py
> Fix multiple clients

- lib_comfyui/comfyui_process.py
- lib_comfyui/ipc/payload.py
- lib_comfyui/webui/settings.py
close #170
This also adds `"listen"` to the list of cmd args that trigger the reverse proxy. It seems to make sense to include it.
> Add warning

- lib_comfyui/comfyui_process.py
- lib_comfyui/ipc/strategies.py
> add executable location

- javascript/compute-height.js
make the reload button set the src of iframes instead of just resetting it.
> reload interfaces button sets the src url

- lib_comfyui/webui/patches.py
https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.7.0-RC
> remove `re_param_code` patch for webui==1.7.0

- install.py
- lib_comfyui/comfyui/pre_main.py
- lib_comfyui/global_state.py
- lib_comfyui/webui/proxies.py
- requirements.txt
> kill comfyui server on webui exit

- lib_comfyui/custom_extension_injector.py
> Update list index when patching the server (#199)

- .gitmodules
> Delete docs directory
